[package]
name = "safe-nlt"
version = "0.0.1"
description = "SAFE API"
authors = ["Gabriel Viganotti <gabrielviganotti@gmail.com>"]
license = "MIT OR BSD-3-Clause"
repository = "https://github.com/maidsafe/safe-network-launch-tool.git"
edition = "2018"

[dependencies]
directories = "2.0.2"
env_logger = "~0.7.1"
log = "~0.4.8"
regex = "1.3.4"
structopt = "~0.3.9"
