[package]
name = "sn_launch_tool"
version = "0.0.12"
description = "SAFE API"
authors = [ "Gabriel Viganotti <gabrielviganotti@gmail.com>" ]
license = "MIT OR BSD-3-Clause"
repository = "https://github.com/maidsafe/sn_launch_tool.git"
edition = "2018"

[dependencies]
directories = "2.0.2"
env_logger = "~0.7.1"
log = "~0.4.8"
structopt = "~0.3.9"
